apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: mycert-webdomain-com 
spec:
  duration: 10h
  renewBefore: 5h
  secretName: mycert-webdomain-com-tls
  dnsNames:
  - mycert.webdomain.com
  usages:
    - server auth
  issuerRef:
    name: vault-issuer
    kind: ClusterIssuer
    group: cert-manager.io