kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vault-auth-token-reviewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "system:auth-delegator"
subjects:
- kind: ServiceAccount
  name: vault-auth-token-reviewer
  namespace: kube-system 
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth-token-reviewer
  namespace: kube-system
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-auth-token-reviewer-token
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: "vault-auth-token-reviewer"
type: kubernetes.io/service-account-token
data: {}