apiVersion: v1
kind: ServiceAccount
metadata:
  name: env-test
---
apiVersion: v1
kind: Pod
metadata:
 name: env-test
 annotations:
  vault.security.banzaicloud.io/vault-addr: "http://vault:8200"
  vault.security.banzaicloud.io/vault-role: env-test_default
  vault.security.banzaicloud.io/vault-env-passthrough: "VAULT_PATH,VAULT_ADDR,VAULT_ROLE"
spec:
  containers:
  - name: env-test
    image: vandesu/env:0 
    # image: nginx
    env:
    - name: SECRET 
      value: vault:env-test/data/database#pass#1
      # value: vault:env-test_kv1/database#pass
    # - name: TOKEN
      # value: vault:login
  serviceAccountName: env-test
