version: '3.8'

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    environment:
      SERVICES: s3,lambda,cloudformation
      DEBUG: 1
      S3_PORT: 4566
      EDGE_PORT: 4566
      DATA_DIR: /tmp/localstack/data
      PORT_WEB_UI: 8080
      LAMBDA_EXECUTOR: docker-reuse
      DOCKER_HOST: unix:///var/run/docker.sock
    ports:
      - "4566:4566"
      - "4571:4571"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - localstack_data:/tmp/localstack
    networks:
      - localstack

  test:
    build: ./test
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
      - TF_VAR_region=us-east-1
      - TF_VAR_bucket_name=my-terratest-bucket
      - TF_VAR_website_index_document=index.html
      - TF_VAR_website_error_document=index.html
    volumes:
      - ".:/workspace"
    depends_on:
      - localstack

volumes:
  localstack_data:

networks:
  localstack:
    name: localstack