---
apiVersion: org.com/v1alpha1
kind: XKubernetesVaultAuth
metadata:
  name: vcluster1
spec:
  kubernetesHost: https://argo-control-plane:6443
---
apiVersion: org.com/v1alpha1
kind: XKubernetesVaultAuth
metadata:
  name: vcluster2
spec: 
  kubernetesHost: https://argo-control-plane:6443