---
# used to use the client service service account token to autenticate to the kube api token review service
# this allows to use short lived token, but requires rbac permissions for each service account to be added to the role.
# more infos here: https://developer.hashicorp.com/vault/docs/auth/kubernetes#how-to-work-with-short-lived-kubernetes-tokens
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-client-auth-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: vault-client-service-accounts
- kind: ServiceAccount
  name: vault-client
  namespace: default